### ISSUE TITLE
Oracle backend

### ISSUE THREAD

**Issue by samh** [beachmachine/django-jython#8]
What would it take to bring back support for Oracle? I looked at the existing drivers briefly, but I'm not sure where to start.

**Comment by beachmachine** [comment]
Hi!

The reason why the oracle backend is not included in django-jython any more is, that I have nearly no experience with oracle, and do not own a license of this software. 

If you are interested in bringing back the oracle support, I think the most easy way is to start from Django's own Oracle backend. Copy it to the django-jython source code, an replace code that is related to `cx_Oracle` with code that works with JDBC. Basically this is what the classes in `doj.db.backens` module are for. django-jython comes with some test cases to check if your backend is working - you find them in `doj.tests.db`.

I hope this gives you a good starting point. It would be great if you could bring back the support for Oracle on django-jython! :-)

**Comment by samh** [comment]
Thanks for the explanation! I don't know if I'll be able to implement it to the point where it can be supported, given my limited use, but we'll see.
